def scmVars

pipeline {
  agent {
    kubernetes {
      yaml """
apiVersion: v1
kind: Pod
spec:
 hostAliases:
  - ip: "10.124.126.30"
    hostnames:
    - "chm-gitlab.ibank.co.th"
  - ip: "100.100.200.7"
    hostnames:
    - "chm-sonarqube.ibank.co.th"
    - "chm-trivy.ibank.co.th"
 containers:
 - name: docker
   image: docker:24.0.6-dind
   command:
   tty: true
   securityContext:
     privileged: true
 - name: helm
   image: lachlanevenson/k8s-helm:v3.5.0
   command:
   - cat
   tty: true
 - name: java-node
   image: timbru31/java-node:17-alpine-jre-14
   command:
   - cat
   tty: true
 - name: bom
   image: node:latest
   command:
   - cat
   tty: true
 - name: trivy
   image: aquasec/trivy:latest
   command:
   - cat
   tty: true
 - name: ruby
   image: jruby:9.4.4.0-jre17
   command:
   - cat
   tty: true
   volumeMounts:
   - name: dependency-check-data
     mountPath: /home/jenkins/dependency-check-data
 volumes:
 - name: dependency-check-data
   hostPath:
     path: /tmp/dependency-check-data
"""
    }    
  }
  environment {
    ENV_NAME = "${BRANCH_NAME == "main" ? "uat" : "${BRANCH_NAME}"}"
    SCANNER_HOME = tool 'sonarqube-scanner'
    PROJECT_KEY = "bookinfo-details"
    PROJECT_NAME = "bookinfo-details"
  }
    stages {
      stage('Clone details source code'){
        steps {
            container('jnlp') {
              script {
                      scmVars = git branch: "${BRANCH_NAME}",
                        credentialsId: 'git-deploy-key',
                        url: 'git@chm-gitlab.ibank.co.th:demo/bookinfo/details.git'
                }
            }
         }
      }
      stage('Sonarqube Scanner') {
        steps {
          container('java-node') {
            script {
              withSonarQubeEnv('sonarqube') {
                sh '''${SCANNER_HOME}/bin/sonar-scanner \
                -D sonar.projectKey=${PROJECT_KEY} \
                -D sonar.projectName=${PROJECT_NAME} \
                -D sonar.projectVersion=${BRANCH_NAME}-${BUILD_NUMBER} \
                -D sonar.sources=./src
                '''
              }
              sleep 10
              timeout(time: 2,unit: 'MINUTES') {
                def qg = waitForQualityGate()
                if (qg.status != 'OK' ) {
                  error "Pipeline aborted due to quality gate failure: ${qg.status}"
                }
              }
            }
          }
        }
      }
      stage('OWASP Dependency Check') {
        steps {
          container('ruby') {
            script {
              sh 'gem install bundler:2.0.2 && bundle init  \
                  && bundle install \
                  && gem install bundler-audit && ls'
              status = sh(script: 'bundle-audit check --update src/', returnStatus: true)
              println "Dependency check status: ${status}"
              dependencyCheck(
                additionalArguments: "--data /home/jenkins/dependency-check-data --out dependency-check-report.xml",
                odcInstallation: "dependency-check"
              )
              sh ''' gem install cyclonedx-ruby &&  cyclonedx-ruby -p . '''
              dependencyTrackPublisher artifact: 'bom.xml', projectId: '7b197e72-2863-4a9a-bc6d-78abf5c25b6f', synchronous: true
              dependencyCheckPublisher(
                pattern: 'dependency-check-report.xml'
              )
              sh '''rm -rf src/node_modules src/package-lock.json'''
            }
          }
        }
      }
      stage('Build details Docker Image and push'){
        steps {
          container('docker'){
            script {
              docker.withRegistry('https://registry.hub.docker.com', 'dockerhub') {
                docker.build("ponetagon/demo-workshop:details-${ENV_NAME}").push()
              }
            }
          }
        }
      }
      stage('Trivy') {
        steps {
          container('trivy') {
            script {
              withCredentials([usernamePassword(credentialsId: 'dockerhub', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                sh """
                export TRIVY_USERNAME=$USERNAME
                export TRIVY_PASSWORD=$PASSWORD
                export TRIVY_AUTH_URL="https://registry.hub.docker.com"
                trivy image --server http://chm-trivy.ibank.co.th -f json -o results.json ponetagon/demo-workshop:details-${ENV_NAME}
                """
                recordIssues(tools: [trivy(pattern: 'results.json')])
              }
            }
          }
        }
      }
      stage('Deploy details with helm chart'){
        steps {
          container('helm'){
            script {
              withKubeConfig([credentialsId: 'kubeconfig']) {
                  sh "helm upgrade --install -f k8s/helm/helm-value/values-details-${ENV_NAME}.yaml --wait \
                    --create-namespace --namespace workshop-${ENV_NAME} bookinfo-details-${ENV_NAME} k8s/helm"
              }    
            }      
          }
        }
      }
   }
}
