def scmVars

pipeline {
  agent {
    kubernetes {
      yaml """
apiVersion: v1
kind: Pod
metadata:
  labels:
    admission.datadoghq.com/enabled: "false"
spec:
 hostAliases:
  - ip: "10.124.126.30"
    hostnames:
    - "chm-gitlab.ibank.co.th"
  - ip: "100.100.200.7"
    hostnames:
    - "chm-sonarqube.ibank.co.th"
    - "chm-trivy.ibank.co.th"
 containers:
 - name: docker
   image: docker:24.0.6-dind
   command:
   tty: true
   securityContext:
     privileged: true
 - name: helm
   image: lachlanevenson/k8s-helm:v3.5.0
   command:
   - cat
   tty: true
 - name: python
   image: python:3.10.12
   command:
   - cat
   tty: true
 - name: trivy
   image: aquasec/trivy:latest
   command:
   - cat
   tty: true
 - name: java-node
   image: timbru31/java-node:latest
   command:
   - cat 
   tty: true
"""
    }    
  }
  environment {
    ENV_NAME = "${BRANCH_NAME == "main" ? "uat" : "${BRANCH_NAME}"}"
    SCANNER_HOME = tool 'sonarqube-scanner'
    PROJECT_KEY = "bookinfo-productpage"
    PROJECT_NAME = "bookinfo-productpage"
  }
    stages {
      stage('Clone productpage source code'){
        steps {
            container('jnlp') {
              script {
                      scmVars = git branch: "${BRANCH_NAME}",
                        credentialsId: 'git-deploy-key',
                        url: 'git@chm-gitlab.ibank.co.th:demo/bookinfo/productpage.git'
                }
            }
         }
      }
      stage('Sonarqube Scanner') {
        steps {
          container('java-node') {
            script {
              withSonarQubeEnv('sonarqube') {
                sh '''${SCANNER_HOME}/bin/sonar-scanner \
                -D sonar.projectKey=${PROJECT_KEY} \
                -D sonar.projectName=${PROJECT_NAME} \
                -D sonar.projectVersion=${BRANCH_NAME}-${BUILD_NUMBER} \
                -D sonar.sources=./source
                ''' 
              }
              timeout(time: 1,unit: 'MINUTES') {
                def qg = waitForQualityGate()
                if (qg.status != 'OK' ) {
                  error "Pipeline aborted due to quality gate failure: ${qg.status}"
                } 
              }
            }
          }
        }
      }  
      stage('OWASP Dependency Track') {
        steps {
          container('python') {
            script {
              sh '''cd source/ && pip install cyclonedx-bom && python3 -m cyclonedx_py -r -o bom.xml '''
              dependencyTrackPublisher artifact: 'source/bom.xml', projectId: '90535e79-f454-4705-b931-52e49de5b726', synchronous: true
            }
          }
        }
      }
      stage('Build productpage Docker Image and push'){
        steps {
          container('docker'){
            script {
              docker.withRegistry('https://registry.hub.docker.com', 'dockerhub') {
                docker.build("ponetagon/demo-workshop:productpage-${ENV_NAME}").push()
              }
            }
          }
        }
      }
      stage('Trivy') {
        steps {
          container('trivy') {
            script {
              withCredentials([usernamePassword(credentialsId: 'dockerhub', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                sh """
                export TRIVY_USERNAME=$USERNAME
                export TRIVY_PASSWORD=$PASSWORD
                export TRIVY_AUTH_URL="https://registry.hub.docker.com"
                trivy image --server http://chm-trivy.ibank.co.th -f json -o results.json ponetagon/demo-workshop:productpage-${ENV_NAME}
                """
                recordIssues(tools: [trivy(pattern: 'results.json')])
              }
            }
          }
        }
      }
      stage('Deploy productpage with helm chart'){
        steps {
          container('helm'){
            script {
              withKubeConfig([credentialsId: 'kubeconfig']) {
                  sh "helm upgrade --install -f k8s/helm/helm-value/values-productpage-${ENV_NAME}.yaml --wait \
                    --namespace workshop-${ENV_NAME} bookinfo-productpage-${ENV_NAME} k8s/helm"
              }    
            }      
          }
        }
      }
   }
}

