def scmVars

pipeline {
  agent {
    kubernetes {
      yaml """
apiVersion: v1
kind: Pod
spec:
 containers:
 - name: docker
   image: docker:24.0.6-dind
   command:
   tty: true
   securityContext:
     privileged: true
 - name: helm
   image: lachlanevenson/k8s-helm:v3.5.0
   command:
   - cat
   tty: true
 - name: skan
   image: alcide/skan:v0.9.0-debug
   command:
   - cat
   tty: true
 - name: trivy
   image: aquasec/trivy:latest
   command:
   - cat
   tty: true 
 - name: java
   image: timbru31/java-node:17-alpine-jre-14
   command:
   - cat
   tty: true
   volumeMounts:
   - name: dependency-check-data
     mountPath: /home/jenkins/dependency-check-data
 - name: gradle
   image: gradle:jdk17
   command:
   - cat 
   tty: true
 volumes:
 - name: dependency-check-data
   hostPath:
     path: /tmp/dependency-check-data
"""
    }    
  }
  environment {
    ENV_NAME = "${BRANCH_NAME == "main" ? "uat" : "${BRANCH_NAME}"}"
    SCANNER_HOME = tool 'sonarqube-scanner'
    PROJECT_KEY = "bookinfo-reviews"
    PROJECT_NAME = "bookinfo-reviews"
  }
    stages {
      stage('Clone reviews source code'){
        steps {
            container('jnlp') {
              script {
                      scmVars = git branch: "${BRANCH_NAME}",
                        credentialsId: 'bookinfo-deploy-key',
                        url: 'git@gitlab-01.opsta-workshop-pontakon.dedyn.io:workshop/bookinfo/reviews.git'
                }
            }
         }
      }
      stage("skan") {
        steps {
          container("helm") { 
            script {
              sh """
              helm template -f k8s/helm/helm-value/values-reviews-${ENV_NAME}.yaml \
                   --namespace workshop-${ENV_NAME} bookinfo-reviews-${ENV_NAME} \
                   --set extraEnv.COMMIT_ID=${scmVars.GIT_COMMIT} k8s/helm \
                   > k8s-manifest-deploy.yaml
                   """
            }
          }
          container("skan") {
            script {
              sh "/skan manifest -f k8s-manifest-deploy.yaml"
              archiveArtifacts artifacts: 'skan-result.html'
              sh "rm k8s-manifest-deploy.yaml"
            }
          }
        }
      }
      stage('Sonarqube Scanner') {
        steps {
          container('gradle') {
            script {
            sh 'gradle build'
              withSonarQubeEnv('sonarqube') {
                sh '''${SCANNER_HOME}/bin/sonar-scanner \
                -D sonar.projectKey=${PROJECT_KEY} \
                -D sonar.projectName=${PROJECT_NAME} \
                -D sonar.projectVersion=${BRANCH_NAME}-${BUILD_NUMBER} \
                -D sonar.sources=./src \
                -D sonar.java.binaries=./build/classes
                ''' 
              }
              sleep 10
              timeout(time: 1,unit: 'MINUTES') {
                def qg = waitForQualityGate()
                if (qg.status != 'OK' ) {
                  error "Pipeline aborted due to quality gate failure: ${qg.status}"
                } 
              }
            }
          }
        }
      }  
      stage('OWASP Dependency Check') {
        steps {
          container('java') {
            script {
              sh '''cd source'''
              dependencyCheck(
                additionalArguments: "--data /home/jenkins/dependency-check-data --out dependency-check-report.xml",  
                odcInstallation: "dependency-check"
              )
              dependencyCheckPublisher(
                pattern: 'dependency-check-report.xml'
              )
            }
          }
        }
      }

      stage('Build reviews Docker Image and push'){
        steps {
          container('docker'){
            script {
              docker.withRegistry('https://harbor.opsta-workshop-pontakon.dedyn.io', 'registry-bookinfo') {
                docker.build("harbor.opsta-workshop-pontakon.dedyn.io/workshop/reviews:${ENV_NAME}").push()
              }
            }
          }
        }
      }
      stage('Trivy') {
        steps {
          container('trivy') {
            script {
              withCredentials([usernamePassword(credentialsId: 'registry-bookinfo', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                sh """
                export TRIVY_USERNAME=$USERNAME
                export TRIVY_PASSWORD=$PASSWORD
                export TRIVY_AUTH_URL="https://harbor.opsta-workshop-pontakon.dedyn.io"
                trivy -f json -o results.json image harbor.opsta-workshop-pontakon.dedyn.io/workshop/reviews:${ENV_NAME}
                """
                recordIssues(tools: [trivy(pattern: 'results.json')])
              }
            }
          }
        }
      }
      stage('Deploy reviews with helm chart'){
        steps {
          container('helm'){
            script {
              withKubeConfig([credentialsId: 'kubeconfig']) {
                  sh "helm upgrade --install -f k8s/helm/helm-value/values-reviews-${ENV_NAME}.yaml --wait \
                    --namespace workshop-${ENV_NAME} bookinfo-reviews-${ENV_NAME} k8s/helm"
              }    
            }      
          }
        }
      }
   }
}
