apiVersion: v1
description: Bookinfo Ratings Service Helm Chart
name: bookinfo-ratings
version: 1.0.0
appVersion: 1.0.0
home: https://bookinfo-rating.opsta-workshop-pontakon.dedyn.io
maintainers:
  - name: Pontakon
    email: pontakon.k@opsta.co.th
sources:
  - https://gitlab.opsta-workshop-pontakon.dedyn.io/workshop/bookinfo/ratings
