details:
  namespace: workshop-dev
  image: harbor.opsta-workshop-pontakon.dedyn.io/workshop/details
  tag: dev
  replicas: 1
  imagePullSecrets: secret-registry-bookinfo-dev
  port: 9080
  healthCheckPath: "/health"
ingess:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  ingressClassName: nginx
  host: bookinfo-details-dev.opsta-workshop-pontakon.dedyn.io
  path: "/"
  serviceType: ClusterIP
  secret_tls: bookinfo-details-dev
